
TextStyle1 0x1110560,"『市長、宇宙に舞う！』\n～\e"
TextStyle1 0x111057A,"発シムプレス～\n\nその有能さによって名高い\n\e"
TextStyle1 0x11105A4,"市長の街、\n\e"
TextStyle1 0x11105B0,"がエクソダスアルコで\n宇宙に進出を始めた。\n\n前述の\e"
TextStyle1 0x11105E2,"市長は、\n有能なスタッフと共に\e"
TextStyle1 0x1110600,"を\n人口１８万人をこえる巨大な街に育てた。\n\nそして、\e"
TextStyle1 0x1110634,"年にはとうとう\n宇宙移民計画エクソダスを実行に移した。\nこの計画はエクソダスアルコと呼ばれる\n完全環境都市を静止軌道上に浮かべて\n人類の生活の場を作りだそうという\n野心的かつ高度な計画である。\n\n宇宙移民第１陣のオーケストラ指揮者の\nエリッヒ・ツァンさんはこう語った。\n『いやあ、\e"
TextStyle1 0x1110744,"市長の\n　見事なタクトさばきには感心するよ。\n　宇宙にまで進出するなんてブラボーだね』\n\nこのような、素晴らしい活躍を見せてくれた\n\e"
TextStyle1 0x11107C4,"市長はまさに\n世界で最も有能な市長であるといえよう。\e"
TextStyle1 0x11107F8,"『国際時代到来』\n～\e"
TextStyle1 0x111080C,"発シムプレス～\n\nその有能さによって名高い\n\e"
TextStyle1 0x1110836,"市長の街、\n\e"
TextStyle1 0x1110842,"は国内でも\n最大規模を誇る国際都市となった。\n\n前述の\e"
TextStyle1 0x1110876,"市長は、\n有能なスタッフと共に\e"
TextStyle1 0x1110894,"を\n人口１８万人をこえる巨大な街に育てた。\n\nそして、\e"
TextStyle1 0x11108C8,"年現在では都市間の\n交通の要所として多くの都市との交流を司る\n国際都市としてその名を高めている。\n特に\e"
TextStyle1 0x111092C,"のカーニバルは\nその国際色豊かなパレードで人気が高く、\nわざわざカーニバルのために\n街を訪れる人もいるほどである。\n\nトラベル・コーディネーターの\nローラ・ドミンゴさんはこう語った。\n『そうネ、この街はとってもキレイだから\n　旅行するにはサイコーよネ。\n　もし行くならカーニバルの時期を\n　強くオススメするわネ』\n\nこのような、素晴らしい活躍を見せてくれた\n\e"
TextStyle1 0x1110A86,"市長は世界最高の\n国際的市長と言っても過言ではないだろう。\e"
TextStyle1 0x1110AC0,"『\e"
TextStyle1 0x1110AC3,"でアロハ！』\n～\e"
TextStyle1 0x1110AD3,"発シムプレス～\n\nその有能さによって名高い\n\e"
TextStyle1 0x1110AFD,"市長の街、\n\e"
TextStyle1 0x1110B09,"は国内でも\n最大規模のリゾート都市である。\n\n前述の\e"
TextStyle1 0x1110B3B,"市長は\n有能なスタッフと共に\e"
TextStyle1 0x1110B57,"を\n人口１８万人をこえる巨大な街に育て上げた。\n\nそして、\e"
TextStyle1 0x1110B8F,"年現在では\n非常に多数の娯楽施設を抱えた\n総合リゾート都市としてその名を高めている。\n特に、マリーナは人気の中心であり、\n活気に溢れる歓声が絶えることはない。\n\n有閑マダムのロクサーヌ・モンローさんは\nこう語った。\n『この街の魅力と言ったら、マリーナよねぇ。\n　たくさんボートがあるって最高ねぇん。\n　ところで記者さん、イイ男ねぇん……』\n\nこのような、素晴らしい活躍を見せてくれた\nブラボーな\e"
TextStyle1 0x1110D0D,"市長に乾杯！\e"
TextStyle1 0x1110D1C,"『市長、ライオンと歓談』\n～\e"
TextStyle1 0x1110D38,"発シムプレス～\n\nその有能さによって名高い\n\e"
TextStyle1 0x1110D62,"市長の街、\n\e"
TextStyle1 0x1110D6E,"は国内でも\n最高レベルのエコロジー政策をとっている。\n\n前述の\e"
TextStyle1 0x1110DAA,"市長は、\n有能なスタッフと共に\e"
TextStyle1 0x1110DC8,"を\n人口１８万人をこえる巨大な街に育てた。\n\nそして、\e"
TextStyle1 0x1110DFC,"年現在では、\n過去の教訓を生かし、\n自然と共に生きることを政策目標に掲げる。\n街中では動物と話の出来る市民が増加し、\n果ては植物とさえ会話出来る者も出ている。\n\n古物収集家のウー・インさんはこう語った。\n『はい、今までもの言わぬとされていた者達が\n　本当はたいへんに雄弁であるという事実は、\n　我々の生活にも大きな影響があります。\n　そう、我々はもう顔に向かって飛んでくる\n　ゴキブリを制止することが出来るのです！』\n\nこのような、素晴らしい活躍を見せてくれた\n\e"
TextStyle1 0x1110FBD,"市長はまさに、\n地球に最も優しい市長といえよう。\e"

; 1110560	1110FF0	
; 1		『市長、宇宙に舞う！』\LineBreak\〜発シムプレス〜\LineBreak\\LineBreak\その有能さによって名高い\LineBreak\市長の街、\LineBreak\がエクソダスアルコで\LineBreak\宇宙に進出を始めた。\LineBreak\\LineBreak\前述の市長は、\LineBreak\有能なスタッフと共にを\LineBreak\人口１８万人をこえる巨大な街に育てた。\LineBreak\\LineBreak\そして、年にはとうとう\LineBreak\宇宙移民計画エクソダスを実行に移した。\LineBreak\この計画はエクソダスアルコと呼ばれる\LineBreak\完全環境都市を静止軌道上に浮かべて\LineBreak\人類の生活の場を作りだそうという\LineBreak\野心的かつ高度な計画である。\LineBreak\\LineBreak\宇宙移民第１陣のオーケストラ指揮者の\LineBreak\エリッヒ・ツァンさんはこう語った。\LineBreak\『いやあ、市長の\LineBreak\見事なタクトさばきには感心するよ。\LineBreak\宇宙にまで進出するなんてブラボーだね』\LineBreak\\LineBreak\このような、素晴らしい活躍を見せてくれた\LineBreak\市長はまさに\LineBreak\世界で最も有能な市長であるといえよう。\End\
; 2		『国際時代到来』\LineBreak\〜発シムプレス〜\LineBreak\\LineBreak\その有能さによって名高い\LineBreak\市長の街、\LineBreak\は国内でも\LineBreak\最大規模を誇る国際都市となった。\LineBreak\\LineBreak\前述の市長は、\LineBreak\有能なスタッフと共にを\LineBreak\人口１８万人をこえる巨大な街に育てた。\LineBreak\\LineBreak\そして、年現在では都市間の\LineBreak\交通の要所として多くの都市との交流を司る\LineBreak\国際都市としてその名を高めている。\LineBreak\特にのカーニバルは\LineBreak\その国際色豊かなパレードで人気が高く、\LineBreak\わざわざカーニバルのために\LineBreak\街を訪れる人もいるほどである。\LineBreak\\LineBreak\トラベル・コーディネーターの\LineBreak\ローラ・ドミンゴさんはこう語った。\LineBreak\『そうネ、この街はとってもキレイだから\LineBreak\旅行するにはサイコーよネ。\LineBreak\もし行くならカーニバルの時期を\LineBreak\強くオススメするわネ』\LineBreak\\LineBreak\このような、素晴らしい活躍を見せてくれた\LineBreak\市長は世界最高の\LineBreak\国際的市長と言っても過言ではないだろう。\End\
; 3		『でアロハ！』\LineBreak\〜発シムプレス〜\LineBreak\\LineBreak\その有能さによって名高い\LineBreak\市長の街、\LineBreak\は国内でも\LineBreak\最大規模のリゾート都市である。\LineBreak\\LineBreak\前述の市長は\LineBreak\有能なスタッフと共にを\LineBreak\人口１８万人をこえる巨大な街に育て上げた。\LineBreak\\LineBreak\そして、年現在では\LineBreak\非常に多数の娯楽施設を抱えた\LineBreak\総合リゾート都市としてその名を高めている。\LineBreak\特に、マリーナは人気の中心であり、\LineBreak\活気に溢れる歓声が絶えることはない。\LineBreak\\LineBreak\有閑マダムのロクサーヌ・モンローさんは\LineBreak\こう語った。\LineBreak\『この街の魅力と言ったら、マリーナよねぇ。\LineBreak\たくさんボートがあるって最高ねぇん。\LineBreak\ところで記者さん、イイ男ねぇん……』\LineBreak\\LineBreak\このような、素晴らしい活躍を見せてくれた\LineBreak\ブラボーな市長に乾杯！\End\
; 4		『市長、ライオンと歓談』\LineBreak\〜発シムプレス〜\LineBreak\\LineBreak\その有能さによって名高い\LineBreak\市長の街、\LineBreak\は国内でも\LineBreak\最高レベルのエコロジー政策をとっている。\LineBreak\\LineBreak\前述の市長は、\LineBreak\有能なスタッフと共にを\LineBreak\人口１８万人をこえる巨大な街に育てた。\LineBreak\\LineBreak\そして、年現在では、\LineBreak\過去の教訓を生かし、\LineBreak\自然と共に生きることを政策目標に掲げる。\LineBreak\街中では動物と話の出来る市民が増加し、\LineBreak\果ては植物とさえ会話出来る者も出ている。\LineBreak\\LineBreak\古物収集家のウー・インさんはこう語った。\LineBreak\『はい、今までもの言わぬとされていた者達が\LineBreak\本当はたいへんに雄弁であるという事実は、\LineBreak\我々の生活にも大きな影響があります。\LineBreak\そう、我々はもう顔に向かって飛んでくる\LineBreak\ゴキブリを制止することが出来るのです！』\LineBreak\\LineBreak\このような、素晴らしい活躍を見せてくれた\LineBreak\市長はまさに、\LineBreak\地球に最も優しい市長といえよう。\End\
