.warning "text_6BEE60.asm scripts are missing"
; 6BEE60	6BEF78	
; 1		毒ガスマスク男\LineBreak\\End\
; 2		MName市長\LineBreak\\End\
; 3		\End\
; 4		ピエロ\LineBreak\\End\
; 5		MName市長\LineBreak\\End\
; 6		\End\
; 7		\End\
; 8		\End\
; 9		探検家\LineBreak\\End\
; 10		MName市長\LineBreak\\End\
; 11		\End\
; 12		\End\
; 13		\End\
; 14		あつあつボーイ\LineBreak\\End\
; 15		あつあつガール\LineBreak\\End\
; 16		MName市長\LineBreak\\End\
; 17		\End\
; 18		くまのマカリスター\LineBreak\\End\
; 19		おそろしいクマ\LineBreak\\End\
; 20		MName市長\LineBreak\\End\
; 21		読書家\LineBreak\\End\
; 22		MName市長\LineBreak\\End\
; 23		\End\
; 24		\End\
; 25		\End\
; 26		生徒\LineBreak\\End\
; 27		MName市長\LineBreak\\End\
; 28		\End\
; 29		\End\
; 30		\End\
; 31		チンピラ\LineBreak\\End\
; 32		MName市長\LineBreak\\End\
